const crypto = require('node:crypto');

function createAiApi({ storage, parseBody, json }) {
  const id = prefix => `${prefix}_${crypto.randomUUID()}`;
  const tokenize = text => [...new Set(String(text || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').match(/[a-z0-9]{3,}/g) || [])];
  const sentence = text => String(text || '').trim().replace(/\s+/g, ' ').replace(/(^.|[.!?]\s+.)/g, value => value.toUpperCase());
  const issueBy = (state, value) => state.issues.find(item => item.id === value || item.key === value);
  const version = (req, body, state) => Number(String(req.headers['if-match'] || req.headers['x-state-version'] || body.version || state.meta.version).replace(/"/g, ''));
  return async function handle(req, res, url, account) {
    if (req.method !== 'POST') return false;
    const body = await parseBody(req); const state = await storage.getState();
    if (url.pathname === '/api/ai/task-summary') { const issue = issueBy(state, body.issueId); if (!issue) return json(res, 404, { error: 'Tarefa não encontrada.' }); const spent = (issue.worklogs || []).reduce((sum, log) => sum + Number(log.minutes || 0), 0); return json(res, 200, { summary: `${issue.key}: ${issue.title}. Status: ${issue.status}; prioridade: ${issue.priority}; responsável: ${state.members.find(member => member.id === issue.assignee)?.name || 'não definido'}; estimativa: ${Number(issue.points || 0)} pontos; tempo registrado: ${spent} minutos.`, risks: [issue.due && new Date(issue.due) < new Date() && issue.status !== 'done' ? 'Prazo vencido' : null, !issue.assignee ? 'Sem responsável' : null, !issue.description ? 'Descrição incompleta' : null].filter(Boolean), mode: 'local' }); }
    if (url.pathname === '/api/ai/generate-description') { const title = sentence(body.title); if (!title) return json(res, 400, { error: 'Informe o título.' }); return json(res, 200, { description: `Objetivo\n${title}.\n\nContexto\n${sentence(body.context || 'Esta entrega faz parte das prioridades atuais do projeto.')}\n\nCritérios de aceite\n- O comportamento esperado foi implementado.\n- Os cenários principais e de erro foram validados.\n- A documentação relevante foi atualizada.`, mode: 'local' }); }
    if (url.pathname === '/api/ai/subtasks') { const issue = issueBy(state, body.issueId); if (!issue) return json(res, 404, { error: 'Tarefa não encontrada.' }); const suggestions = [`Analisar requisitos de ${issue.title}`, `Implementar ${issue.title}`, `Criar testes para ${issue.title}`, `Documentar e validar ${issue.title}`]; if (!body.create) return json(res, 200, { suggestions, mode: 'local' }); if (account.roleId === 'viewer') return json(res, 403, { error: 'Acesso somente leitura.' }); const project = state.projects.find(item => item.id === issue.projectId); const created = suggestions.map((title, index) => ({ id: id('issue'), key: `${project.key}-${Math.max(0, ...state.issues.filter(item => item.projectId === project.id).map(item => Number(String(item.key).split('-').pop()) || 0)) + index + 1}`, projectId: issue.projectId, parentId: issue.id, title, description: '', type: 'subtask', priority: issue.priority || 'medium', status: 'todo', assignee: issue.assignee || null, reporter: account.memberId, sprintId: issue.sprintId || null, points: 0, labels: ['ai-assisted'], created: new Date().toISOString(), updated: new Date().toISOString(), order: state.issues.length + index + 1, comments: [], worklogs: [] })); state.issues.push(...created); state.currentUser = account.memberId; const saved = await storage.saveState(state, version(req, body, state)); return json(res, 201, { subtasks: created, version: saved.meta.version, mode: 'local' }); }
    if (url.pathname === '/api/ai/automation-suggestion') { const issue = issueBy(state, body.issueId); if (!issue) return json(res, 404, { error: 'Tarefa não encontrada.' }); const suggestions = []; if (issue.priority === 'highest' || issue.priority === 'high') suggestions.push({ name: 'Escalonar trabalho prioritário', trigger: { type: 'issue.created' }, conditions: [{ field: 'priority', operator: 'contains', value: 'high' }], actions: [{ type: 'add-label', value: 'expedite' }, { type: 'comment', text: 'Item prioritário encaminhado para triagem.' }] }); if (!issue.assignee) suggestions.push({ name: 'Atribuir itens sem responsável', trigger: { type: 'issue.created' }, conditions: [{ field: 'assignee', operator: 'is-empty' }], actions: [{ type: 'add-label', value: 'needs-owner' }] }); return json(res, 200, { suggestions, mode: 'local' }); }
    if (url.pathname === '/api/ai/smart-search') { const queryTokens = tokenize(body.query); const results = state.issues.map(issue => { const text = `${issue.key} ${issue.title} ${issue.description} ${(issue.labels || []).join(' ')} ${issue.epic || ''}`; const tokens = tokenize(text); const score = queryTokens.reduce((sum, token) => sum + (tokens.some(value => value.includes(token) || token.includes(value)) ? 1 : 0), 0); return { issue, score }; }).filter(item => item.score > 0).sort((a, b) => b.score - a.score).slice(0, Math.min(50, Number(body.limit || 20))); return json(res, 200, { results, mode: 'local' }); }
    if (url.pathname === '/api/ai/comments-summary') { const issue = issueBy(state, body.issueId); if (!issue) return json(res, 404, { error: 'Tarefa não encontrada.' }); const comments = issue.comments || []; const authors = [...new Set(comments.map(comment => state.members.find(member => member.id === comment.author)?.name || comment.author))]; const recent = comments.slice(-3).map(comment => sentence(comment.text)); return json(res, 200, { summary: comments.length ? `${comments.length} comentário(s), com participação de ${authors.join(', ')}. Pontos recentes: ${recent.join(' | ')}` : 'Ainda não há comentários para resumir.', commentCount: comments.length, mode: 'local' }); }
    if (url.pathname === '/api/ai/writing-assistant') { const text = sentence(body.text); if (!text) return json(res, 400, { error: 'Informe o texto.' }); let rewritten = text; if (body.tone === 'concise') rewritten = text.split(/(?<=[.!?])\s+/).slice(0, 2).join(' '); if (body.tone === 'formal') rewritten = sentence(rewritten.replace(/\bvc\b/gi, 'você').replace(/\bpra\b/gi, 'para')); return json(res, 200, { text: rewritten, tone: body.tone || 'clear', mode: 'local' }); }
    return false;
  };
}

module.exports = { createAiApi };
