const crypto = require('node:crypto');

function createEcosystemApi({ storage, parseBody, json }) {
  const id = prefix => `${prefix}_${crypto.randomUUID()}`;
  const hash = value => crypto.createHash('sha256').update(value).digest('hex');
  const version = (req, body, state) => Number(String(req.headers['if-match'] || req.headers['x-state-version'] || body.version || state.meta.version).replace(/"/g, ''));
  async function save(req, body, state, account, text) { state.currentUser = account.memberId; state.activity = state.activity || []; state.activity.unshift({ id: id('activity'), user: account.memberId, text, date: new Date().toISOString() }); return storage.saveState(state, version(req, body, state)); }
  const adminOnly = (res, account) => { if (account.roleId === 'admin') return false; json(res, 403, { error: 'Acesso restrito a administradores.' }); return true; };
  const catalogs = {
    integrations: ['Microsoft Teams', 'Slack', 'Outlook', 'Google Workspace', 'GitHub', 'GitLab', 'Jenkins', 'Azure DevOps', 'Salesforce', 'Power BI'],
    marketplace: ['Gestão financeira', 'Timesheet', 'Riscos', 'Gantt', 'PMO', 'CRM', 'RH', 'BI', 'IA Generativa', 'Aprovações'],
    testProviders: ['Xray Test Management', 'Zephyr Scale'], devopsProviders: ['GitHub', 'GitLab', 'Bitbucket'],
  };
  return async function handle(req, res, url, account) {
    const pageRoute = url.pathname.match(/^\/api\/knowledge(?:\/([^/]+))?$/);
    if (pageRoute) { const state = await storage.getState(); state.knowledgePages = state.knowledgePages || []; const pageId = pageRoute[1] ? decodeURIComponent(pageRoute[1]) : null; if (req.method === 'GET') { if (pageId) { const page = state.knowledgePages.find(item => item.id === pageId); return page ? json(res, 200, { page }) : json(res, 404, { error: 'Página não encontrada.' }); } const type = url.searchParams.get('type'); return json(res, 200, { pages: type ? state.knowledgePages.filter(item => item.type === type) : state.knowledgePages }); } if (account.roleId === 'viewer') return json(res, 403, { error: 'Acesso somente leitura.' }); const body = await parseBody(req); if (req.method === 'POST' && !pageId) { if (!body.title || !['documentation', 'requirement', 'wiki', 'knowledge-base'].includes(body.type)) return json(res, 400, { error: 'Título e tipo válido são obrigatórios.' }); const page = { id: id('page'), title: body.title.trim(), type: body.type, content: String(body.content || ''), projectId: body.projectId || null, labels: body.labels || [], authorId: account.memberId, version: 1, history: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; state.knowledgePages.push(page); const saved = await save(req, body, state, account, `criou a página ${page.title}`); return json(res, 201, { page, version: saved.meta.version }); } const index = state.knowledgePages.findIndex(item => item.id === pageId); if (index < 0) return json(res, 404, { error: 'Página não encontrada.' }); const page = state.knowledgePages[index]; if (req.method === 'PATCH' || req.method === 'PUT') { page.history.push({ version: page.version, title: page.title, content: page.content, authorId: account.memberId, savedAt: new Date().toISOString() }); Object.assign(page, body, { id: page.id, version: page.version + 1, updatedAt: new Date().toISOString() }); const saved = await save(req, body, state, account, `atualizou a página ${page.title}`); return json(res, 200, { page, version: saved.meta.version }); } if (req.method === 'DELETE') { state.knowledgePages.splice(index, 1); const saved = await save(req, body, state, account, `excluiu a página ${page.title}`); return json(res, 200, { ok: true, version: saved.meta.version }); } }
    if (url.pathname === '/api/devops/events' && req.method === 'POST') { const state = await storage.getState(); const body = await parseBody(req); if (!['commit', 'pull-request', 'branch', 'deployment', 'pipeline'].includes(body.type)) return json(res, 400, { error: 'Tipo de evento DevOps inválido.' }); const text = `${body.title || ''} ${body.message || ''} ${body.ref || ''}`; const keys = [...new Set(text.match(/[A-Z][A-Z0-9]+-\d+/g) || [])]; const issueIds = state.issues.filter(issue => keys.includes(issue.key)).map(issue => issue.id); state.devopsEvents = state.devopsEvents || []; const event = { id: id('devops'), provider: body.provider || 'GitHub', type: body.type, title: body.title || body.message || body.ref, url: body.url || null, status: body.status || null, issueIds, payload: body.payload || {}, createdAt: new Date().toISOString() }; state.devopsEvents.unshift(event); const saved = await save(req, body, state, account, `registrou evento DevOps ${event.type}`); return json(res, 201, { event, version: saved.meta.version }); }
    if (url.pathname === '/api/devops/events' && req.method === 'GET') { const state = await storage.getState(); const issueId = url.searchParams.get('issueId'); return json(res, 200, { events: (state.devopsEvents || []).filter(item => !issueId || item.issueIds.includes(issueId)) }); }
    if (url.pathname === '/api/api-keys' && req.method === 'POST') { if (adminOnly(res, account)) return; const state = await storage.getState(); const body = await parseBody(req); const token = `orb_${crypto.randomBytes(32).toString('base64url')}`; state.apiKeys = state.apiKeys || []; const apiKey = { id: id('api_key'), name: String(body.name || 'Integração'), tokenHash: hash(token), scopes: Array.isArray(body.scopes) ? body.scopes : ['read'], active: true, createdBy: account.memberId, createdAt: new Date().toISOString() }; state.apiKeys.push(apiKey); const saved = await save(req, body, state, account, `criou a chave de API ${apiKey.name}`); return json(res, 201, { apiKey: { ...apiKey, tokenHash: undefined }, token, warning: 'Copie o token agora; ele não será exibido novamente.', version: saved.meta.version }); }
    if (url.pathname === '/api/api-keys' && req.method === 'GET') { if (adminOnly(res, account)) return; const state = await storage.getState(); return json(res, 200, { apiKeys: (state.apiKeys || []).map(({ tokenHash, ...item }) => item) }); }
    if (url.pathname === '/api/catalog' && req.method === 'GET') return json(res, 200, catalogs);
    if (url.pathname === '/api/enterprise/insights' && req.method === 'GET') { const state = await storage.getState(); const activeProjects = state.projects.filter(item => !item.archived); const open = state.issues.filter(item => item.status !== 'done'); return json(res, 200, { portfolio: { projects: activeProjects.length, programs: (state.programs || []).length, openWork: open.length, totalCapacity: (state.capacityPlans || []).reduce((sum, item) => sum + Number(item.capacity || 0), 0), plannedPoints: open.reduce((sum, item) => sum + Number(item.points || 0), 0) }, governance: { auditEntries: (state.activity || []).length, dataResidency: state.enterpriseSettings?.dataResidency || 'Brazil', sandboxes: (state.sandboxes || []).length } }); }
    const configs = {
      'devops-connections': { key: 'devopsConnections', admin: true, prefix: 'devops_connection' },
      'test-cases': { key: 'testCases', admin: false, prefix: 'test_case' }, 'test-plans': { key: 'testPlans', admin: false, prefix: 'test_plan' }, 'test-executions': { key: 'testExecutions', admin: false, prefix: 'test_execution' },
      'integration-connections': { key: 'integrationConnections', admin: true, prefix: 'integration' }, 'webhooks': { key: 'webhookSubscriptions', admin: true, prefix: 'webhook_subscription' },
      'marketplace/installations': { key: 'marketplaceInstallations', admin: true, prefix: 'app' }, 'programs': { key: 'programs', admin: true, prefix: 'program' }, 'portfolios': { key: 'portfolios', admin: true, prefix: 'portfolio' },
      'capacity-plans': { key: 'capacityPlans', admin: false, prefix: 'capacity' }, 'sandboxes': { key: 'sandboxes', admin: true, prefix: 'sandbox' },
    };
    const match = url.pathname.match(/^\/api\/(devops-connections|test-cases|test-plans|test-executions|integration-connections|webhooks|marketplace\/installations|programs|portfolios|capacity-plans|sandboxes)(?:\/([^/]+))?$/);
    if (match) { const cfg = configs[match[1]], state = await storage.getState(); state[cfg.key] = state[cfg.key] || []; const itemId = match[2] ? decodeURIComponent(match[2]) : null; if (req.method === 'GET') return json(res, 200, { items: state[cfg.key].map(item => ({ ...item, secret: item.secret ? '••••••••' : undefined })), version: state.meta.version }); if ((cfg.admin && adminOnly(res, account)) || account.roleId === 'viewer') return json(res, 403, { error: 'Permissão insuficiente.' }); const body = await parseBody(req); if (req.method === 'POST' && !itemId) { const item = { ...body, id: id(cfg.prefix), createdBy: account.memberId, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; delete item.version; if (item.secret) item.secretHash = hash(item.secret), delete item.secret; state[cfg.key].push(item); const saved = await save(req, body, state, account, `criou registro em ${match[1]}`); return json(res, 201, { item: { ...item, secretHash: undefined }, version: saved.meta.version }); } const index = state[cfg.key].findIndex(item => item.id === itemId); if (index < 0) return json(res, 404, { error: 'Registro não encontrado.' }); if (req.method === 'PATCH' || req.method === 'PUT') { const update = { ...body }; delete update.version; if (update.secret) update.secretHash = hash(update.secret), delete update.secret; state[cfg.key][index] = { ...state[cfg.key][index], ...update, id: itemId, updatedAt: new Date().toISOString() }; const saved = await save(req, body, state, account, `atualizou registro em ${match[1]}`); return json(res, 200, { item: { ...state[cfg.key][index], secretHash: undefined }, version: saved.meta.version }); } if (req.method === 'DELETE') { state[cfg.key].splice(index, 1); const saved = await save(req, body, state, account, `removeu registro de ${match[1]}`); return json(res, 200, { ok: true, version: saved.meta.version }); } }
    if (url.pathname === '/api/enterprise/settings' && req.method === 'GET') { const state = await storage.getState(); return json(res, 200, { settings: state.enterpriseSettings || { dataResidency: 'Brazil', advancedAudit: true, crossProjectPlanning: true } }); }
    if (url.pathname === '/api/enterprise/settings' && (req.method === 'PATCH' || req.method === 'PUT')) { if (adminOnly(res, account)) return; const state = await storage.getState(); const body = await parseBody(req); state.enterpriseSettings = { ...(state.enterpriseSettings || {}), ...body }; delete state.enterpriseSettings.version; const saved = await save(req, body, state, account, 'atualizou configurações corporativas'); return json(res, 200, { settings: state.enterpriseSettings, version: saved.meta.version }); }
    return false;
  };
}

module.exports = { createEcosystemApi };
